### ISSUE TITLE
reconstruction and EDM4Hep output.

### ISSUE THREAD

**Issue by gaswk** [key4hep/k4MarlinWrapper#109]
Dear all,

I have some questions regarding the reconstruction and EDM4Hep output. I would like to have some assistance if possible.
My problem is that I get a segmentation violation error every time I run the reconstruction and this with different input files. I use the file fccRec_e4h_input.py
I don't have this error if I remove the PodioOutput algorithm.

More precisely the error I get is:

*** Break *** segmentation violation 
Error in <TTree::SetBranchAddress>: unknown branch -> LumiCalClusters
 
But it doesn't seem to have problem in the LumiCalCollections in all my files.
The error occurs whether or not there are hits in the LumiCal for all events.
I have files with hits in the LumiCal for each event and files with some events with no hits in the LumiCal. I always get the same error.

It crashes at some point depending on the input file, some files crashes on the first event. It also always crashes on the same event depending on the input file.

If I remove the PodioOutput algorithm then I don’t get error and also if I let the PodioOutput algorithm and remove the LumiCal reconstruction algorithm then I don’t get error either

The command I use is:
k4run fccRec_e4h_input.py  --EventDataSvc.input  bbbar_edm4hep.root  -n 100

I hope this is clear.

Has anyone had this problem ?
And maybe know what the problem is and how to fix it

**Comment by andresailer** [comment]
* How do you set up the key4hep stack?
* you are using this file https://github.com/key4hep/k4MarlinWrapper/blob/master/test/gaudi_opts/fccRec_e4h_input.py without any changes?
* How do you create the bbbar_edm4hep.root file? Can you make this file available?

**Comment by gaswk** [comment]
I source at:
 source /cvmfs/sw.hsf.org/key4hep/setup.sh

Yes I am using this file https://github.com/key4hep/k4MarlinWrapper/blob/master/test/gaudi_opts/fccRec_e4h_input.py without any change

Here the commamd to get bbbar_edm4hep.root input file:

curl https://transfer.sh/WpPjdE/bbSIM_edm4hep.root -o bbSIM_edm4hep.root

But as I explained I have the same issue for different input files, this was just an example

**Comment by andresailer** [comment]
Unlike the CLIC reconstruction, this uses a different Marlin Processor for the LumiCal Reconstruction.
That one didn't always write out its collections, fixed with https://github.com/FCALSW/FCalClusterer/pull/71
