### ISSUE TITLE
 Broken associations when using edm4hep input 

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/k4MarlinWrapper#113]
For details see https://github.com/key4hep/k4LCIOReader/issues/31

Maybe this is not worth fixing and we should directly switch to https://github.com/key4hep/k4EDM4hep2LcioConv/pull/11? What is the status on that?

**Comment by tmadlener** [comment]
That one is effectively ready, in the sense that we don't expect any real API changes any longer, unless we find a serious bug. What would be necessary from the k4MarlinWrapper side is to re-implement the wrapping (and talking to Gaudi) using that. It should in principle be rather similar to the EDM4hep -> LCIO direction.

**Comment by Zehvogel** [comment]
Is there a timeline for when the integration into k4marlinWrapper will be done?

**Comment by tmadlener** [comment]
Not really yet. The main problem is having the time to implement the wrapping. Technically it should be rather straight forward. The earliest I can have a look is probably in two-ish weeks.

**Comment by Zehvogel** [comment]
@tmadlener can you provide an update on this?

**Comment by tmadlener** [comment]
Still no progress, unfortunately. I will start looking into this now.

**Comment by Zehvogel** [comment]
@jmcarcell maybe also something to add to https://github.com/key4hep/key4hep-spack/issues/502?
