### ISSUE TITLE
Unexpected Resolution Improvement in CLD Performance Plots when removing calorimeters

### ISSUE THREAD

**Issue by gaswk** [key4hep/k4MarlinWrapper#116]
I am currently working on reproducing CLD performance plots. I tried to remove the calorimeters in order to speed up the simulation process. This modification has resulted in unexpected results.

The resolution I obtained without the calorimeters is several orders of magnitude better than when including them. To illustrate this, I have attached a plot as an example. The plot includes data points obtained with all detectors at theta values of 10, 30, 50, 70, and 89 degrees. Additionally, I have included points from a simulation performed solely with the trackers, using theta values of 20, 40, 60, and 80 degrees.

To achieve this, I commented out the following lines in the FCCee_o2_v02.xml file:

```
<!-- <include ref="ECalBarrel_o2_v01_03.xml"/>
    <include ref="ECalEndcap_o2_v01_03.xml"/> -->

    <!-- <include ref="HCalBarrel_o1_v01_01.xml"/>
    <include ref="HCalEndcap_o1_v01_01.xml"/> -->

    <include ref="Solenoid_o1_v01_02.xml"/>

    <!-- <include ref="YokeBarrel_o1_v01_02.xml"/>
    <include ref="YokeEndcap_o1_v01_02.xml"/> -->
```

and those ones in fccRec_e4h_input.py:

```inp = PodioInput('InputReader')
inp.collections = [
  'EventHeader',
  'MCParticles',
  'VertexBarrelCollection',
  'VertexEndcapCollection',
  'InnerTrackerBarrelCollection',
  'OuterTrackerBarrelCollection',
  #'ECalEndcapCollection',
  #'ECalEndcapCollectionContributions',
  #'ECalBarrelCollection',
  #'ECalBarrelCollectionContributions',
  #'HCalBarrelCollection',
  #'HCalBarrelCollectionContributions',
  'InnerTrackerEndcapCollection',
  'OuterTrackerEndcapCollection',
  #'HCalEndcapCollection',
  #'HCalEndcapCollectionContributions',
  #'HCalRingCollection',
  #'HCalRingCollectionContributions',
  #'YokeBarrelCollection',
  #'YokeBarrelCollectionContributions',
  #'YokeEndcapCollection',
  #'YokeEndcapCollectionContributions',
  'LumiCalCollection',
  'LumiCalCollectionContributions',
]
inp.OutputLevel = WARNING
```
![momentum_resolution_theta_mu](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/d9eb72b5-9c92-47af-bb30-d74b7985095d)

To reproduce the issue, please follow these steps:  https://github.com/gaswk/FullSim/tree/main/TrackingPerformance

**Comment by andresailer** [comment]
Given that the "normal" resolutions are what we more or less expect given material and single point resolutions. I wager something else is going wrong. What do the distributions going into the individual points look like?

**Comment by gaswk** [comment]
Do you mean the Delta(pT/pT^2) distributions? If yes, here some of them

![mu_10deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/c358e8a3-49ec-4ba7-abab-2c9a972379fb)
![mu_20deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/bd6fe159-0dee-4c25-a381-f796be192b20)
![mu_30deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/9984c912-3307-48c6-ae82-15070fd845ce)
![mu_40deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/eb3ce5cc-b077-4a4d-9154-56970818d806)
![mu_50deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/129e5672-9b51-422b-8a41-465218cbe03f)
![mu_60deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/9cc8b93e-b47f-4d17-a74f-5b0def3cdc32)
![mu_70deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/df29cc8b-5bb9-468a-ba56-cee9d9cdb4b5)
![mu_80deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/db394748-3bd8-42e6-8b10-1b8e007ee3b5)
![mu_89deg_100GeV_1000evt root](https://github.com/key4hep/k4MarlinWrapper/assets/116810451/470f4d31-8d3a-4d48-a175-8aa20d2df7ec)

**Comment by andresailer** [comment]
I guess those with a huge bias are those without the calorimeters?

**Comment by gaswk** [comment]
As mentioned earlier, theta values 10, 30, 50, 70, and 89 deg are with calorimeters. And theta values of 20, 40, 60, and 80 deg are without calorimeters. You can easily identify the corresponding theta values in the titles of the plots

**Comment by andresailer** [comment]
Yeah, right, sorry!
But also huge bias, so the results are just not good without calorimeters.
Of course the why...

**Comment by andresailer** [comment]
What happens if you include the ECAL Barrel and Endcap in the geometry for the reconstruction?

**Comment by gaswk** [comment]
For the reconstruction if I include the calorimeters I get an error because of the missing collections

**Comment by andresailer** [comment]
Only for the geometry, not the digitisers, those don't matter.

**Comment by Zehvogel** [comment]
Hi Gaelle, I am just guessing but have you checked if the collection ids that you hardcoded in the creation of your tree are still the same when you leave out the calorimeters?

**Comment by gaswk** [comment]
Hi Leonhard, well spotted! the collections ids have indeed changed, and I haven't thought of that... I just redo the plots with the correct ids and everything seems fine. 
Sorry!
