### ISSUE TITLE
Always convert EventHeader collection

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/k4MarlinWrapper#153]
otherwise one can forget about it and then event numbers etc. are missing leading to the same symptoms as https://github.com/key4hep/k4MarlinWrapper/issues/110

**Comment by tmadlener** [comment]
Can you be a bit more specific on what the issue is, or how to reproduce it? In principle the EventHeader should be converted unless this information is already there. However, it seems that this is not working as intended, or that something is missing?

**Comment by Zehvogel** [comment]
Copying how to read and convert edm4hep files from the below test leads to missing event numbers as the EventHeader collection is not converted. One can argue that this works as intended as the EventHeader collection is not listed there but I think we would always want to convert it as it is  not a normal collection in the lcio world.
https://github.com/key4hep/k4MarlinWrapper/blob/5e6bb7c6e59c974614bac91139f5107945a7f78f/test/gaudi_opts/fccRec_e4h_input.py#L78-L97

**Comment by tmadlener** [comment]
Ah, now I get it. That makes sense. That should be fairly straight forward to fix by simply adding one line (plus a comment) before the `if` here: https://github.com/key4hep/k4MarlinWrapper/blob/5e6bb7c6e59c974614bac91139f5107945a7f78f/k4MarlinWrapper/src/components/EDM4hep2Lcio.cpp#L318-L320

Do you have any easy test that could also be added alongside with the fix? And do you have the time to implement the fix? (It will become end of this week at least for me).

**Comment by Zehvogel** [comment]
Time for the fix maybe, easy test not so much. In principle we would need to check the lcio output to have consistent event numbers but as far as I can see that already requires multiple steps?
