### ISSUE TITLE
Rename to k4MarlinWrapper

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4MarlinWrapper#20]
I think this should affect
- [x] the repository name
- [x] the CMake configuration 
- [x] the spack recipe.

**Comment by vvolkl** [comment]
I don't know if it is necessary to rename the `GMPWrapper` subdirectory. maybe it would be nice if the the library files also start with `libk4` so it is easier to find them in a view.

**Comment by vvolkl** [comment]
Note that this will apparently also change the tarball checksums: https://github.com/key4hep/k4-spack/issues/90

**Comment by fdplacido** [comment]
Good to know about the checksums. To me I prefer to have consistent naming for the subdirectories so I'll say we change it to be consistent in as many places as possible.

**Comment by andresailer** [comment]
As agreed in the last key4hep meeting -> k4MarlinWrapper

**Comment by fdplacido** [comment]
This is now fixed in #23, so the github repo can now change name.
The spack recipe remains to be updated, so I would keep the issue open.
