### ISSUE TITLE
Error make

### ISSUE THREAD

**Issue by alexhxia** [key4hep/k4MarlinWrapper#74]
Hi, I try to do your tutorial, but I have this error :

In file included from ~/k4MarlinWrapper/k4MarlinWrapper/k4MarlinWrapper/converters/EDM4hep2Lcio.h:17,
                 from ~/k4MarlinWrapper/k4MarlinWrapper/src/components/EDM4hep2Lcio.cpp:1:
/home/ilc/ahocine/k4MarlinWrapper/k4MarlinWrapper/k4MarlinWrapper/LCEventWrapper.h:27:10: fatal error: EVENT/LCEvent.h: No such file or directory
   27 | #include <EVENT/LCEvent.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [k4MarlinWrapper/CMakeFiles/EDM4hep2Lcio.dir/build.make:76: k4MarlinWrapper/CMakeFiles/EDM4hep2Lcio.dir/src/components/EDM4hep2Lcio.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1053: k4MarlinWrapper/CMakeFiles/EDM4hep2Lcio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by fdplacido** [comment]
Yes, this is due to some issues with CMake and/or the CVMFS view. There is a PR here that will fix it: https://github.com/key4hep/k4MarlinWrapper/pull/73
