### ISSUE TITLE
Documentation Improvement suggestions

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4MarlinWrapper#80]
* In https://github.com/key4hep/k4MarlinWrapper/tree/master/doc/starterkit/k4MarlinWrapperCLIC#reconstruction-with-edm4hep-input,  it's easy to miss the line explaining where to get `clicRec_e4h_input.py`
* Typo: `with with` in https://github.com/key4hep/k4MarlinWrapper/tree/master/doc/starterkit/k4MarlinWrapperCLIC#reconstruction-with-with-gaudi-through-k4marlinwrapper
* The docs for the conversion etc. could be added to the main key4hep page also.

**Comment by fdplacido** [comment]
I believe this is now covered in https://github.com/key4hep/k4MarlinWrapper/pull/89
