### ISSUE TITLE
Error `event_display.py`

### ISSUE THREAD

**Issue by alexhxia** [key4hep/k4MarlinWrapper#88]
Hello,

I find a typing mistake in your new file `k4MarlinWrapper/k4MarlinWrapper/examples/event_display.py` in lines 79-80 : 
```
"TPCCollection", "0", "3", "1", "
SETCollection", "0", "3", "1",
```
Best regards.

**Comment by tmadlener** [comment]
Ah, indeed that looks like something I introduced when reformatting it before committing. It should be easy to fix by moving the double quotes `"` to the right place. Does it break anything, or are some collections simply not displayed?

**Comment by alexhxia** [comment]
With this correction, I have no error anymore.

**Comment by tmadlener** [comment]
Would you be able to open a pull request with the fix?

**Comment by alexhxia** [comment]
I think it is good.
