### ISSUE TITLE
Improvement in documentation

### ISSUE THREAD

**Issue by armin-ilg** [key4hep/k4MarlinWrapper#90]
Hi there

When running through the instructions on clicReconstruction with EDM4hep listed in [here](https://key4hep.github.io/key4hep-doc/k4marlinwrapper/doc/starterkit/k4MarlinWrapperCLIC/Readme.html), I stumpled over the line
`cp ../../../test/gaudi_opts/clicRec_e4h_input.py .
`
To make this more clear, I'd replace the line in the [README](https://github.com/key4hep/k4MarlinWrapper/tree/master/doc/starterkit/k4MarlinWrapperCLIC#readme) with 
`cp ../../k4MarlinWrapper/test/gaudi_opts/clicRec_e4h_input.py .
`
so that it actually points to the correct file (if the k4MarlinWrapper repo is actually called "k4MarlinWrapper" at least.

**Comment by andresailer** [comment]
Hi Armin,

Thanks for the issue! It is true that in the webpage the context to k4MarlinWrapper is lost, and it is not clear where this file comes to. We have to add a step about either cloning k4MarlinWrapper, or a different way to get this steering file.
