### ISSUE TITLE
Calorimeter hits problem following in CLIC reco recipe

### ISSUE THREAD

**Issue by ebrondol** [key4hep/k4MarlinWrapper#98]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: centos7
 - key4hep version: nightly tag of 2022/11/28
 - Package version: commit [7e8f0e0](https://github.com/key4hep/k4MarlinWrapper/commit/7e8f0e04e9c2577019332f3ddd0866acb10b26e5)
 - Reproduced by: I have followed the recipe in the k4MarlinWrapperCLIC [web page](https://key4hep.github.io/key4hep-doc/k4marlinwrapper/doc/starterkit/k4MarlinWrapperCLIC/Readme.html)
 - Input: Input files `clicRec_e4h_input.py` and `ttbar_edm4hep.root` in:
`/afs/cern.ch/user/e/ebrondol/public/k4MarlinWrapper/Issue/`
with debug printout `podio_dump_ttbar_edm4hep.log`
 - Output: Output files `my_output.root` and `Output_REC_k4run_edm4hep.slcio` in
`/afs/cern.ch/user/e/ebrondol/public/k4MarlinWrapper/Issue/`
with debug printout `podio_dump_my_output.log` and `anajob_Output_REC_k4run_edm4hep.log`, respectively .
Log file of the running process in `k4run_reco_edm4hep.log`
 - Goal: In the output SLCIO file all calorimeters collections (sim & reco) are empty. In the output edm4hep file the sim calorimeter hits are correctly there, while the reco calo hits are not.
- Additional info: I have tried to test the full reco chain with SLCIO as input and output and it works fine, so the problem is not in the wrapping or content of the single processors.

**Comment by tmadlener** [comment]
So one thing we figured out by now is that `OverlayFalse`
https://github.com/key4hep/k4MarlinWrapper/blob/7e8f0e04e9c2577019332f3ddd0866acb10b26e5/test/gaudi_opts/clicRec_e4h_input.py#L1778
kills all `SimCalorimeterHits` that are in the event up until that point. Removing that from the algorithms that are run, solves that issue, but there are the calo digitizers still don't seem to produce any output, so it only solves some part of the problem.

**Comment by ebrondol** [comment]
Another debugging result is that if we do not use the `convertAll`, 
```
edmConvTool.convertAll = False
edmConvTool.collNameMapping = {
                              "ECalBarrelCollection": "ECalBarrelSim",
                              "ECalEndcapCollection": "ECalEndcapSim"
}
```
these two collections are shown filled correctly in the output slcio file:
```
---------------------------------------------------------------------------
COLLECTION NAME               COLLECTION TYPE          NUMBER OF ELEMENTS
===========================================================================
ECalBarrelSim                 SimCalorimeterHit             6113
ECalEndcapSim                 SimCalorimeterHit             2701
---------------------------------------------------------------------------
```

**Comment by andresailer** [comment]
This is converting at the AIDAProcessor? What if you call them ECalBarrelCollection, etc., in LCIO? Then the overlay will still drop all their hits?

**Comment by ebrondol** [comment]
Yes, it is [this point](https://github.com/key4hep/k4MarlinWrapper/blob/7e8f0e04e9c2577019332f3ddd0866acb10b26e5/test/gaudi_opts/clicRec_e4h_input.py#L75-L79) in the config file.
Here is if I use the same name as the input for the Barrel part:
```
---------------------------------------------------------------------------
COLLECTION NAME               COLLECTION TYPE          NUMBER OF ELEMENTS
===========================================================================
ECalBarrelCollection          SimCalorimeterHit                0
ECalEndcapSim                 SimCalorimeterHit             2701
---------------------------------------------------------------------------
```
while if I comment the `OverlayFalse` processor, both collections are shown correctly:
```
---------------------------------------------------------------------------
COLLECTION NAME               COLLECTION TYPE          NUMBER OF ELEMENTS
===========================================================================
ECalBarrelCollection          SimCalorimeterHit             6113
ECalEndcapSim                 SimCalorimeterHit             2701
---------------------------------------------------------------------------
```

**Comment by andresailer** [comment]
The conversion of the CaloHitContributions is not working, all their slcio entries are zeroes.
Then either Overlay kicks out the hits, because their time of 0 is outside the window after time-of-flight correction. Or the Digitiser doens't digitise them because their energy is 0.

**Comment by tmadlener** [comment]
re-opening, since the real fix is in the other PR.

**Comment by ebrondol** [comment]
Hi @andresailer @tmadlener , 
thanks for the prompt fix. There is still one issue ongoing, but it was there also in the previous version of the package.

The Simulated Calo hits total number differs between the `slcio` and the `emd4hep` output file. In the following tables I am including also the reco CaloHits just for bookkeeping:
- `Output_REC.slcio`:
```
ECALBarrel                    CalorimeterHit                4364
ECALEndcap                    CalorimeterHit                2241
ECalBarrelCollection          SimCalorimeterHit             4684
ECalEndcapCollection          SimCalorimeterHit             2385
```
- `my_output.root` :
```
ECALBarrel                     edm4hep::CalorimeterHit                  4364
ECALEndcap                     edm4hep::CalorimeterHit                  2241
ECalBarrelCollection           edm4hep::SimCalorimeterHit               5647
ECalEndcapCollection           edm4hep::SimCalorimeterHit               2955
```
My guess after all the lessons learned by this issue, is that it can be related to the `OverlayFalse` module that is changing the SIM CaloHits but the changes are not propagated in the EDM4HEP DM. 
From my side, this follow-up is not urgent.

**Comment by andresailer** [comment]
Hi @ebrondol 
Here the OverlayProcessor removes some hits from the LCIO collection, there is no way to do this on the EDM4hep side.
I think for the EDM4hep flow we cannot modify the collections read from a file, and the overlay algorithm will have to create new collections as output? @tmadlener might correct me of course?

In any case an EDM4hep based overlay processor would be quite important to have so that we can feed edm4hep files as background as well.

**Comment by tmadlener** [comment]
> I think for the EDM4hep flow we cannot modify the collections read from a file, and the overlay algorithm will have to create new collections as output?

That is correct.

In principle it might be possible to workaround this if necessary (I haven't tested this, I just think it should work.). As you see it is a bit cumbersome.
- In the input conversion map the `SimCalorimeterHit` collections to another name, e.g.
```python
edmConvTool.convertAll = True
edmConvTool.collNameMapping = {
  'ECalBarrelCollection': 'ECalBarrelCollectionFull',
  'ECalEndcapCollection': 'ECalEndcapCollectionFull',
  # and so on for other collections
}
```
- Adapt the overlay processor to take the `Full` collections as inputs
- Run a LCIO -> EDM4hep converter, attached to the Overlay processor, with the reverse name mapping (or in this case, just add more collections to the existing one)
```python
  'ECalBarrelCollectionFull': 'ECalBarrelCollection',
  'ECalEndcapCollectionFull': 'ECalEndcapCollection',
  # and so on or other collectios
```
- Finally to also make the "regular" collections visible to LCIO as well, run another EDM4hep -> LCIO converter, converting back the regular collections. Now the LCIO event will have these collections duplicated with different names.

If there is a processor that can simply rename collections, than the last step could be replaced by that, but I don't know of one that does this.

**Comment by andresailer** [comment]
> If there is a processor that can simply rename collections, than the last step could be replaced by that, but I don't know of one that does this.

https://github.com/key4hep/k4MarlinWrapper/blob/7e8f0e04e9c2577019332f3ddd0866acb10b26e5/test/gaudi_opts/clicRec_e4h_input.py#L1816

Well, kind of ~~abuse~~ creative use of the Merge Collections processor :)

Though in python you could also script around the collection names
